# Generated by Django 2.1.1 on 2019-06-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='scope',
        ),
        migrations.AddField(
            model_name='scope',
            name='articles_scope',
            field=models.ManyToManyField(related_name='scopes', through='articles.ArticleScope', to='articles.Article'),
        ),
    ]
