# Generated by Django 2.1 on 2019-06-29 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190628_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='articles_scope',
            new_name='articles',
        ),
    ]
