# Generated by Django 2.1 on 2019-06-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20190629_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlescope',
            old_name='scope',
            new_name='topic',
        ),
    ]
