# Generated by Django 2.1 on 2019-06-29 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20190629_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='articles',
            new_name='scopes',
        ),
    ]
